version: 2.1

workflows:
  build-workflow:
    jobs:
      - build:
          context:
            - deployment

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm ci && npm run postinstall #https://discuss.circleci.com/t/build-fail-with-circleci-node-latest/37885
      - run:
          name: commitlint
          command: npx --no-install commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run postinstall && npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npx --no-install semantic-release
